# docker-compose.yml

version: '3.8'

services:
  system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG_FILE=/app/logs/system.log
